-- Lua workspace libraries. Hyprland (0.55+) ships autogenerated stubs for
-- its `hl` Lua config API, so add them when installed for autocompletion
-- and type checking of hyprland.lua files.
local lua_library = {
	vim.env.VIMRUNTIME,
	"${3rd}/luv/library",
	"${3rd}/busted/library",
}
if vim.fn.isdirectory("/usr/share/hypr/stubs") == 1 then
	table.insert(lua_library, "/usr/share/hypr/stubs")
end

return {
	settings = {
		Lua = {
			runtime = {
				version = "LuaJIT",
			},
			completion = {
				callSnippet = "Replace",
			},
			diagnostics = {
				globals = { "vim", "hl" },
			},
			workspace = {
				library = lua_library,
				checkThirdParty = false,
			},
			telemetry = {
				enable = false,
			},
			format = {
				enable = false, -- Use stylua instead
			},
		},
	},
}
