return {
	"stevearc/aerial.nvim",
	dependencies = {
		"nvim-treesitter/nvim-treesitter",
		"nvim-tree/nvim-web-devicons",
	},
	keys = {
		{ "<leader>a", "<cmd>AerialToggle<cr>", desc = "Toggle Outline (Aerial)" },
		{ "[a", "<cmd>AerialPrev<cr>", desc = "Previous symbol" },
		{ "]a", "<cmd>AerialNext<cr>", desc = "Next symbol" },
	},
	config = function()
		require("aerial").setup({
			backends = { "treesitter", "lsp", "markdown", "man" },
			layout = {
				max_width = { 40, 0.2 },
				width = nil,
				min_width = 20,
				default_direction = "prefer_right",
				placement = "edge",
			},
			attach_mode = "global",
			close_automatic_events = {},
			keymaps = {
				["?"] = "actions.show_help",
				["g?"] = "actions.show_help",
				["<CR>"] = "actions.jump",
				["<2-LeftMouse>"] = "actions.jump",
				["o"] = "actions.jump",
				["<C-v>"] = "actions.jump_vsplit",
				["<C-s>"] = "actions.jump_split",
				["p"] = "actions.scroll",
				["<M-j>"] = "actions.down_and_scroll",
				["<M-k>"] = "actions.up_and_scroll",
				["{"] = "actions.prev",
				["}"] = "actions.next",
				["[["] = "actions.prev_up",
				["]]"] = "actions.next_up",
				["q"] = "actions.close",
				["za"] = "actions.tree_toggle",
				["zA"] = "actions.tree_toggle_recursive",
				["l"] = "actions.tree_open",
				["L"] = "actions.tree_open_recursive",
				["h"] = "actions.tree_close",
				["H"] = "actions.tree_close_recursive",
				["zr"] = "actions.tree_increase_fold_level",
				["zR"] = "actions.tree_open_all",
				["zm"] = "actions.tree_decrease_fold_level",
				["zM"] = "actions.tree_close_all",
				["zx"] = "actions.tree_sync_folds",
				["zX"] = "actions.tree_sync_folds",
			},
			lazy_load = true,
			filter_kind = false,
			highlight_on_hover = true,
			highlight_on_jump = 300,
			icons = {},
			ignore = {
				filetypes = {},
				buftypes = "special",
				wintypes = "special",
			},
			show_guides = true,
			guides = {
				mid_item = "├─",
				last_item = "└─",
				nested_top = "│ ",
				whitespace = "  ",
			},
		})
	end,
}
